name: Check and test Python package

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-and-test:
    strategy:
      matrix:
        python-version:
            - "3.8"
            - "3.9"
            - "3.10"
            - "3.11"

    name: Check and test
    uses: greenbone/workflows/.github/workflows/ci-python.yml@main
    with:
      lint-packages: autohooks tests
      linter: ruff
      python-version: ${{ matrix.python-version }}

  mypy:
    name: Check typing
    uses: greenbone/workflows/.github/workflows/typing-python.yml@main
    with:
      python-version: "3.10"


  codecov:
    name: Upload coverage to codecov.io
    # run action directly because GitHub has an internal error when using our
    # generic reusable workflow
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - name: Install and calculate and upload coverage to codecov.io
        uses: greenbone/actions/coverage-python@v3
        with:
          python-version: "3.10"
          cache: "true"
          token: ${{ secrets.CODECOV_TOKEN }}
